### ISSUE TITLE
Scary behavior from running example in README

### ISSUE THREAD

**Issue by papb** [sindresorhus/random-bytes-readable-stream#1]
Hello, I copypasted the example in README and executed it, and literally my PC started beeping nonstop. I ended up rebooting it to be safe.

My goal was too just see some random stuff printed to console and then hit `Ctrl+C` and stop it, but instead it hanged (nothing printed on stdout) and `Ctrl+C` did not stop the beeping. I tried killing every node process I could find but the beeping didn't stop. I might have missed something obvious though, I got scared and decided to turn it off asap.

Is this any normal?

I am using windows by the way.

-----

By the way, on a side note: a huge thanks for all the great work you've done for JavaScript so far! It's awesome! :grimacing:

**Comment by sindresorhus** [comment]
Hehe. I should probably have limited the size. Fixed now.

I'm not sure why it beeps for you. It might be because some of the random characters create an ansi escape code for the beep sound, or some other cmd.exe-specific reason.

**Comment by papb** [comment]
Awesome, thanks :grin:
